name: Test and Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run Govulncheck
        run: govulncheck ./...
        
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
